controllers/MonitorController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\helpers\Url;

use yii\data\ActiveDataProvider;

use app\models\LoginForm;
use app\models\NewBrandForm;
use app\models\NewSeriesForm;
use app\models\NewPositionForm;
use app\models\NewBindingForm;
use app\models\EditBindingForm;

use app\models\Price;
use app\models\Website;
use app\models\Brand;
use app\models\Series;
use app\models\Position;
use app\models\Log;


class MonitorController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'login', 'index', 'catalogue', 'brand', 'add-position', 'position-monitor', 'error-log', 'export'],
                'rules' => [
                    [
                        'actions' => ['logout', 'index', 'catalogue', 'brand', 'add-position', 'position-monitor', 'error-log', 'export'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['login', 'export'],
                        'allow' => true,
                        'roles' => ['?'],
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $all_positions_count = count(Price::find()->where(["website_id" => 1])->all());
        $makeup_positions_count = count(Price::find()->where(["website_id" => 2])->all());
        $parfums_positions_count = count(Price::find()->where(["website_id" => 4])->all());
        $lagrande_positions_count = count(Price::find()->where(["website_id" => 3])->all());
        $parfumeria_positions_count = count(Price::find()->where(["website_id" => 5])->all());
        
        return $this->render('index', [
            "all_positions_count" => $all_positions_count,
            "makeup_positions_count" => $makeup_positions_count,
            "parfums_positions_count" => $parfums_positions_count,
            "lagrande_positions_count" => $lagrande_positions_count,
            "parfumeria_positions_count" => $parfumeria_positions_count,
        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post(), '') && $model->login()) {
            return $this->goBack();
        }
        return $this->renderPartial('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
    
    public function actionCatalogue()
    {
        $new_brand = new NewBrandForm();
        if ($new_brand->load(Yii::$app->request->post()) && $new_brand->validate()) {
            if (!Brand::findOne(["name" => $new_brand->brandName])) {
                $brand = new Brand([
                    "name" => $new_brand->brandName,
                ]);
                $brand->save();
                Yii::$app->getSession()->setFlash('success', 'Бренд <strong>'.$brand->name.'</strong> был успешно добавлен в систему!');
                return $this->refresh();
            }
            
        }
        
        $brands = new ActiveDataProvider([
            'query' => Brand::find(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
        
        return $this->render('catalogue', [
            'brands' => $brands,
            'new_brand' => $new_brand,
        ]);
    }
    
    public function actionBrand($id, $type = Series::TYPE_MEN)
    {
        $new_series = new NewSeriesForm();
        if ($new_series->load(Yii::$app->request->post()) && $new_series->validate()) {
            if (!Series::findOne(["name" => $new_series->seriesName, "brand_id" => $id, "gender" => $new_series->gender])) {
                $series = new Series([
                    "brand_id" => $id,
                    "name" => $new_series->seriesName,
                    "gender" => $new_series->gender,
                ]);
                $series->save();
                Yii::$app->getSession()->setFlash('success', 'Серия <strong>'.$series->name.'</strong> была успешно добавлена в систему!');
                return $this->refresh();
            }
            
        }
        
        $new_position = new NewPositionForm();
        
        $brand = Brand::findOne($id);
        
        return $this->render('brand', [
            'brand' => $brand,
            'new_series' => $new_series,
            'new_position' => $new_position,
            'type' => $type,
        ]);
    }
    
    public function actionAddPosition() {
        if (Yii::$app->request->isAjax) {
            
            $message['error'] = 1;
            
            $new_position = new NewPositionForm();
            if ($new_position->load(Yii::$app->request->post()) && $new_position->validate()) {
                if (!Position::findOne(["series_id" => $new_position->seriesId, "type" => $new_position->type, "capacity" => $new_position->capacity, "box" => $new_position->box])) {
                    $position = new Position([
                        "series_id" => $new_position->seriesId,
                        "type" => $new_position->type,
                        "capacity" => $new_position->capacity,
                        "box" => $new_position->box,
                    ]);
                    
                    if ($position->save()) {
                        $message['error'] = 0;
                        $message['param'] = [
                            "seriesId" => $new_position->seriesId,
                            "id" => $position->id,
                            "type" => Position::getTypes()[$new_position->type],
                            "capacity" => $new_position->capacity,
                            "box" => Position::getBoxTypes()[$new_position->box],
                        ];
                    }
                }
            }
            
            echo json_encode($message);
        }
    }
    
    public function actionChangeArticle() {
        if (Yii::$app->request->isAjax) {
            
            $response['error'] = 1;
            
            $params = Yii::$app->request->post();
            if (!empty($params['price-id']) && !empty($params['price-article']) && !empty($params['website-id']) && !empty($params['position-id'])) {
                if (is_numeric($params['price-id']) && is_numeric($params['price-article']) && is_numeric($params['website-id']) && is_numeric($params['position-id'])) {

                    /*
                     *  New price:
                     */
                    if ($params['price-id'] == -1) {
                        
                        $price = new Price([
                            "position_id" => $params['position-id'],
                            "website_id" => $params['website-id'],
                            "own_id_data" => $params['price-article'],
                        ]);
                        
                        $result = $price->save();
                        
                    } else {
                        if ($price = Price::find()->where(['id' => $params['price-id'], 'website_id' => $params['website-id']])->one()) {
                            $price->own_id_data = $params['price-article'];
                            $result = $price->save();
                        }
                    }
                    
                    if ($result) {
                        $response['error'] = 0;
                        $response['priceId'] = $price->id;
                        $response['priceArticle'] = $price->own_id_data;
                    }
                    
                    
                }
            }
            
            echo json_encode($response);
        }
    }
    
    public function actionPositionMonitor($position_id, $delete = false) {
        
        /*
         * Delete price:
         */
        if ($delete) {
            if ($price = Price::findOne($delete)) {
                if ($price->delete()) {
                    return $this->redirect(Url::to(['monitor/position-monitor', 'position_id' => $position_id]));
                }
            }
        }
        
        /*
         * Add new binding:
         */
        $new_binding = new NewBindingForm();
        if ($new_binding->load(Yii::$app->request->post()) && $new_binding->validate()) {
            if (!Price::findOne(["position_id" => $new_binding->position_id, "website_id" => $new_binding->website_id])) {
                $price = new Price([
                    "position_id" => $new_binding->position_id,
                    "website_id" => $new_binding->website_id,
                    "id_data" => $new_binding->id_data,
                ]);
                $price->save();
            } else {
                Yii::$app->getSession()->setFlash('error', 'Данный веб-сайт уже имеется в списке!');
            }
        }
        
        /*

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\widgets\Menu;
use yii\helpers\Url;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="hold-transition skin-purple sidebar-mini <?php if (Yii::$app->controller->action->id == "brand") { ?>sidebar-collapse<?php } ?>">
<?php $this->beginBody() ?>

<div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <a href="/" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>С</b>М</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Система</b>Мониторинга</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">

          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
              <img src="/img/bazilik.png" class="user-image" alt="User Image">
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs">Eley.com.ua</span>
            </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
                <img src="/img/bazilik.png" class="img-circle" alt="User Image">

                <p>
                  Eley.com.ua
                  <small>Интернет-магазин парфюмерии</small>
                </p>
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-right">
                  <a data-method="post" href="<?=Url::to(['monitor/logout']); ?>" class="btn btn-default btn-flat">Выход</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="/img/bazilik.png" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>Eley.com.ua</p>
          <!-- Status -->
          <a href="#"><i class="fa fa-circle text-success"></i> Онлайн</a>
        </div>
      </div>

      <!-- search form (Optional) -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Поиск...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->

      <!-- Sidebar Menu -->
    <?php
    echo Menu::widget([
      'items' => [
          ['label' => 'Меню'],
          ['label' => '<i class="fa fa-home"></i> <span>Главная</span>', 'url' => ['monitor/index']],
          ['label' => '<i class="fa fa-registered"></i> <span>Каталог продукции</span>', 'url' => ['monitor/catalogue']],
          ['label' => '<i class="fa fa-shopping-cart"></i> <span>Магазин ELEY</span>', 'url' => ['monitor/eley-shop']],
          ['label' => '<i class="fa fa-money"></i> <span>Проверка цены</span>', 'url' => ['monitor/price-test']],
          ['label' => '<i class="fa fa-check-square-o"></i> <span>Журнал ошибок</span>', 'url' => ['monitor/error-log']],
      ],
      'options' => [
          'class' => 'sidebar-menu',
      ],
      'encodeLabels' => false,
      'firstItemCssClass' => 'header',
    ]);

    ?>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Система мониторинга
        <small>и корректировки цен</small>
      </h1>
      <ol class="breadcrumb" style="display: none;">
        <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
        <li class="active">Here</li>
      </ol>
      <?php
      echo Breadcrumbs::widget([
          'tag' => 'ol',
          'homeLink' => ['label' => '<i class="fa fa-dashboard"></i> Главная', 'url' => ['monitor/index']],
          'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
          'encodeLabels' => false,
      ]);
      ?>
    </section>

    <!-- Main content -->
    <section class="content">
      
        <?php if(Yii::$app->session->hasFlash("success")): ?>
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <p><i class="icon fa fa-check"></i> <?= Yii::$app->session->getFlash("success"); ?></p>
        </div>  
        <?php endif; ?>
        
        <?php if(Yii::$app->session->hasFlash("error")): ?>
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <p><i class="icon fa fa-exclamation"></i> <?= Yii::$app->session->getFlash("error"); ?></p>
        </div>  
        <?php endif; ?>
      
        <?= $content ?>

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Система мониторинга цен
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2016 <a href="http://eley.com.ua">Eley.com.ua</a>.</strong> All rights reserved.
  </footer>
</div>
<!-- ./wrapper -->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>