controllers/MonitorController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\helpers\Url;

use yii\data\ActiveDataProvider;

use app\models\LoginForm;
use app\models\NewBrandForm;
use app\models\NewSeriesForm;
use app\models\NewPositionForm;
use app\models\NewBindingForm;
use app\models\EditBindingForm;

use app\models\Price;
use app\models\Website;
use app\models\Brand;
use app\models\Series;
use app\models\Position;
use app\models\Log;


class MonitorController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'login', 'index', 'catalogue', 'brand', 'add-position', 'position-monitor', 'error-log', 'export'],
                'rules' => [
                    [
                        'actions' => ['logout', 'index', 'catalogue', 'brand', 'add-position', 'position-monitor', 'error-log', 'export'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['login', 'export'],
                        'allow' => true,
                        'roles' => ['?'],
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $all_positions_count = count(Price::find()->where(["website_id" => 1])->all());
        $makeup_positions_count = count(Price::find()->where(["website_id" => 2])->all());
        $parfums_positions_count = count(Price::find()->where(["website_id" => 4])->all());
        $lagrande_positions_count = count(Price::find()->where(["website_id" => 3])->all());
        $parfumeria_positions_count = count(Price::find()->where(["website_id" => 5])->all());
        
        return $this->render('index', [
            "all_positions_count" => $all_positions_count,
            "makeup_positions_count" => $makeup_positions_count,
            "parfums_positions_count" => $parfums_positions_count,
            "lagrande_positions_count" => $lagrande_positions_count,
            "parfumeria_positions_count" => $parfumeria_positions_count,
        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post(), '') && $model->login()) {
            return $this->goBack();
        }
        return $this->renderPartial('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
    
    public function actionCatalogue()
    {
        $new_brand = new NewBrandForm();
        if ($new_brand->load(Yii::$app->request->post()) && $new_brand->validate()) {
            if (!Brand::findOne(["name" => $new_brand->brandName])) {
                $brand = new Brand([
                    "name" => $new_brand->brandName,
                ]);
                $brand->save();
                Yii::$app->getSession()->setFlash('success', 'Бренд <strong>'.$brand->name.'</strong> был успешно добавлен в систему!');
                return $this->refresh();
            }
            
        }
        
        $brands = new ActiveDataProvider([
            'query' => Brand::find(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
        
        return $this->render('catalogue', [
            'brands' => $brands,
            'new_brand' => $new_brand,
        ]);
    }
    
    public function actionBrand($id, $type = Series::TYPE_MEN)
    {
        $new_series = new NewSeriesForm();
        if ($new_series->load(Yii::$app->request->post()) && $new_series->validate()) {
            if (!Series::findOne(["name" => $new_series->seriesName, "brand_id" => $id, "gender" => $new_series->gender])) {
                $series = new Series([
                    "brand_id" => $id,
                    "name" => $new_series->seriesName,
                    "gender" => $new_series->gender,
                ]);
                $series->save();
                Yii::$app->getSession()->setFlash('success', 'Серия <strong>'.$series->name.'</strong> была успешно добавлена в систему!');
                return $this->refresh();
            }
            
        }
        
        $new_position = new NewPositionForm();
        
        $brand = Brand::findOne($id);
        
        return $this->render('brand', [
            'brand' => $brand,
            'new_series' => $new_series,
            'new_position' => $new_position,
            'type' => $type,
        ]);
    }
    
    public function actionAddPosition() {
        if (Yii::$app->request->isAjax) {
            
            $message['error'] = 1;
            
            $new_position = new NewPositionForm();
            if ($new_position->load(Yii::$app->request->post()) && $new_position->validate()) {
                if (!Position::findOne(["series_id" => $new_position->seriesId, "type" => $new_position->type, "capacity" => $new_position->capacity, "box" => $new_position->box])) {
                    $position = new Position([
                        "series_id" => $new_position->seriesId,
                        "type" => $new_position->type,
                        "capacity" => $new_position->capacity,
                        "box" => $new_position->box,
                    ]);
                    
                    if ($position->save()) {
                        $message['error'] = 0;
                        $message['param'] = [
                            "seriesId" => $new_position->seriesId,
                            "id" => $position->id,
                            "type" => Position::getTypes()[$new_position->type],
                            "capacity" => $new_position->capacity,
                            "box" => Position::getBoxTypes()[$new_position->box],
                        ];
                    }
                }
            }
            
            echo json_encode($message);
        }
    }
    
    public function actionChangeArticle() {
        if (Yii::$app->request->isAjax) {
            
            $response['error'] = 1;
            
            $params = Yii::$app->request->post();
            if (!empty($params['price-id']) && !empty($params['price-article']) && !empty($params['website-id']) && !empty($params['position-id'])) {
                if (is_numeric($params['price-id']) && is_numeric($params['price-article']) && is_numeric($params['website-id']) && is_numeric($params['position-id'])) {

                    /*
                     *  New price:
                     */
                    if ($params['price-id'] == -1) {
                        
                        $price = new Price([
                            "position_id" => $params['position-id'],
                            "website_id" => $params['website-id'],
                            "own_id_data" => $params['price-article'],
                        ]);
                        
                        $result = $price->save();
                        
                    } else {
                        if ($price = Price::find()->where(['id' => $params['price-id'], 'website_id' => $params['website-id']])->one()) {
                            $price->own_id_data = $params['price-article'];
                            $result = $price->save();
                        }
                    }
                    
                    if ($result) {
                        $response['error'] = 0;
                        $response['priceId'] = $price->id;
                        $response['priceArticle'] = $price->own_id_data;
                    }
                    
                    
                }
            }
            
            echo json_encode($response);
        }
    }
    
    public function actionPositionMonitor($position_id, $delete = false) {
        
        /*
         * Delete price:
         */
        if ($delete) {
            if ($price = Price::findOne($delete)) {
                if ($price->delete()) {
                    return $this->redirect(Url::to(['monitor/position-monitor', 'position_id' => $position_id]));
                }
            }
        }
        
        /*
         * Add new binding:
         */
        $new_binding = new NewBindingForm();
        if ($new_binding->load(Yii::$app->request->post()) && $new_binding->validate()) {
            if (!Price::findOne(["position_id" => $new_binding->position_id, "website_id" => $new_binding->website_id])) {
                $price = new Price([
                    "position_id" => $new_binding->position_id,
                    "website_id" => $new_binding->website_id,
                    "id_data" => $new_binding->id_data,
                ]);
                $price->save();
            } else {
                Yii::$app->getSession()->setFlash('error', 'Данный веб-сайт уже имеется в списке!');
            }
        }
        
        /*

views/monitor/_brand-row.php
<?php
use yii\helpers\Url;
use app\models\Series;

echo "<tr>
        <td>
            <a href='".Url::to(['monitor/brand', 'id' => $model->id])."'>".$model->name."</a>
        </td>
        <td>
            <div class='category-type'>
                <a href='".Url::to(['monitor/brand', 'id' => $model->id, 'type' => Series::TYPE_MEN])."' class='label label-primary hvr-float-shadow'>Мужская</a>
                <a href='".Url::to(['monitor/brand', 'id' => $model->id, 'type' => Series::TYPE_WOMEN])."' class='label label-danger hvr-float-shadow'>Женская</a>
                <a href='".Url::to(['monitor/brand', 'id' => $model->id, 'type' => Series::TYPE_UNISEX])."' class='label label-warning hvr-float-shadow'>Универсальная</a>
            </div>
        </td>
        <td>".count($model->series)."</td>
      </tr>";

views/monitor/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/monitor/brand.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\helpers\Url;

use app\models\Position;
use app\models\Series;

$this->title = $brand->name;
$this->params['breadcrumbs'][] = ['label' => 'Каталог продукции', 'url' => ['monitor/catalogue']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-sm-5">
        <?php
        foreach (Series::getTypes() as $key => $category_type) {
            
            $collapsed_class = 'collapsed-box';
            $box_tool_sign = 'plus';
            
            switch ($key) {
                case Series::TYPE_MEN:
                    $series = $brand->seriesMen;
                    $box_class = "box-primary";
                    if ($type == Series::TYPE_MEN) { $collapsed_class = ''; $box_tool_sign = 'minus'; }
                    break;
                case Series::TYPE_WOMEN:
                    $series = $brand->seriesWomen;
                    $box_class = "box-danger";
                    if ($type == Series::TYPE_WOMEN) { $collapsed_class = ''; $box_tool_sign = 'minus'; }
                    break;
                case Series::TYPE_UNISEX:
                    $series = $brand->seriesUnisex;
                    $box_class = "box-warning";
                    if ($type == Series::TYPE_UNISEX) { $collapsed_class = ''; $box_tool_sign = 'minus'; }
                    break;
            }
        ?>
        <div class="box <?= $collapsed_class ?> <?= $box_class ?>">
            <div class="box-header with-border">
                <h3 class="box-title"><?= $category_type ?></h3>
                <div class="box-tools pull-right">
                    <button data-widget="collapse" class="btn btn-box-tool" type="button"><i class="fa fa-<?= $box_tool_sign ?>"></i></button>
                </div><!-- /.box-tools -->
            </div><!-- /.box-header -->
            <div class="box-body">
                <table id="series-table" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Бренд</th>
                            <th>Наименование серии</th>
                            <th>К-во позиций</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        if (count($series)) foreach ($series as $a_series) {
                            echo "<tr data-series-id='$a_series->id'>
                                    <td>".$brand->name."</td>
                                    <td>".$a_series->name."</td>
                                    <td>".count($a_series->positions)."</td>
                                  </tr>";
                        } else {
                            echo "<tr><td colspan='3' class='text-center'>В эту категорию ни одна серия не была добавлена</td></tr>";
                        }
                        ?>
                    </tbody>
                </table>
            </div><!-- /.box-body -->
            <div class="box-footer">
                <div class="row">
                    <div class="col-xs-6">
                        <p>Всего серий: <?= count($brand->series) ?></p>
                    </div>
                    <div class="col-xs-6 text-right">
                        <p><a class="btn btn-sm btn-primary left-crop new-series-window-button" data-toggle="modal" data-target="#add-series-modal" data-category="<?=$key?>"><i class="fa fa-plus"></i> Добавить серию</a></p>
                    </div>
                </div>
            </div><!-- box-footer -->
        </div><!-- /.box -->
        <?php } ?>

    </div>
    <div class="col-sm-7 positions-blocks" id="js-positions-blocks">
        <?php foreach ($brand->series as $a_series) { ?>
        <div id="series-<?= $a_series->id ?>" class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Позиции <?= "$brand->name $a_series->name" ?></h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Тип</th>
                            <th>Объем</th>
                            <th>Упаковка</th>
                            <th class="label-primary">Eley.com.ua</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($a_series->positions as $position) {

                            $price = app\models\Price::findOne(["position_id" => $position->id, "website_id" => 1]);
                            
                            if (!$price) {
                                $price_article = "-";
                                $price_id = -1;
                            }
                            else {
                                $price_article = $price->own_id_data;
                                $price_id = $price->id;
                            }

                            echo "<tr>
                                    <td>".Position::getTypes()[$position->type]."</td>
                                    <td>".$position->capacity."</td>
                                    <td>".Position::getBoxTypes()[$position->box]."</td>
                                    <td class='product-article' data-id=''>
                                        <form>
                                            <input name='price-id' value='$price_id' type='hidden' />
                                            <input name='position-id' value='$position->id' type='hidden' />
                                            <input name='website-id' value='1' type='hidden' />
                                            <input name='price-article' type='input' value='$price_article' />
                                        </form>
                                        <span>$price_article</span>
                                    </td>
                                    <td><a target='_blank' href='".Url::to(["monitor/position-monitor", "position_id" => $position->id])."' class='btn btn-xs btn-success monitor'><span class='fa fa-refresh'></span></a></td>
                                    <td><a title='Удалить позицию' href='#' class='remove btn btn-xs btn-info' data-id='".$position->id."'><span class='fa fa-remove'></span></a></td>
                                  </tr>";
                        }
                        ?>
                    </tbody>
                </table>
            </div><!-- /.box-body -->
            <div class="box-footer">
                <div class="row">
                    <div class="col-xs-6">
                        <p>Всего позиций: <?= count($a_series->positions) ?></p>
                    </div>
                    <div class="col-xs-6 text-right">
                        <p><a class="btn btn-sm btn-primary left-crop" data-toggle="modal" data-target="#add-position-modal"><i class="fa fa-plus"></i> Добавить позицию</a></p>
                    </div>
                </div>
            </div><!-- box-footer -->
        </div><!-- /.box -->
        <?php } ?>

    </div>
</div>

<div id="add-series-modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Добавление новой серии</h4>
      </div>
      <div class="modal-body">
        <?php
        $form = \yii\bootstrap\ActiveForm::begin();
        
        echo $form->field($new_series, "seriesName")->textInput();
        echo Html::activeHiddenInput($new_series, "gender");      
        
        $form->end();
        ?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
        <button id="add-new-series-button" type="button" class="btn btn-primary">Добавить</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id="add-position-modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Добавление новой позиции</h4>
      </div>
      <div class="modal-body">
        <?php
        $form = \yii\bootstrap\ActiveForm::begin([
            "action" => Url::to(["monitor/add-position"]),
        ]);
        
        echo $form->field($new_position, "seriesId")->hiddenInput()->label(false);
        
        echo $form->field($new_position, "type")->dropDownList(Position::getTypes(), ['prompt'=>'Выберите тип духов']);
        
        echo $form->field($new_position, "capacity")->textInput();
        
        echo $form->field($new_position, "box")->dropDownList(Position::getBoxTypes(), ['prompt'=>'Выберите упаковку']);
                
        $form->end();
        ?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
        <button id="add-new-position-button" type="button" class="btn btn-primary">Добавить</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

views/monitor/catalogue.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\helpers\Url;
use app\models\Series;
use yii\widgets\ListView;

$this->title = 'Каталог продукции';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Бренды</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <?php $table_layout = '{summary}
            <table class="table table-bordered table-hover brands-list">
                <tbody>
                    <tr>
                        <th>Наименование бренда</th>
                        <th>Быстрый переход</th>
                        <th>Количество серий</th>
                    </tr>
                    {items}
                </tbody>
            </table>
            <div class="pages">{pager}</div>';

            echo ListView::widget([
                'dataProvider' => $brands,
                'layout' => $table_layout,
                'itemView' => '_brand-row',
            ]);

            ?>
    </div><!-- /.box-body -->
    <div class="box-footer">
        <div class="row">
            <div class="col-xs-6"></div>
            <div class="col-xs-6 text-right">
                <p><a class="btn btn-sm btn-primary left-crop" data-toggle="modal" data-target="#add-brand-modal"><i class="fa fa-plus"></i> Добавить бренд</a></p>
            </div>
        </div>
    </div><!-- box-footer -->
</div><!-- /.box -->

<div id="add-brand-modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Добавление нового бренда</h4>
      </div>
      <div class="modal-body">
        <?php
        $form = \yii\bootstrap\ActiveForm::begin();
        
        echo $form->field($new_brand, "brandName")->textInput();
                
        $form->end();
        ?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
        <button id="add-new-brand-button" type="button" class="btn btn-primary">Добавить</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

views/monitor/eley-shop.php
<?php

use yii\helpers\Url;
use \app\models\Price;

/* @var $this yii\web\View */

$this->title = 'Магазин ELEY';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Магазин ELEY</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <p>Здесь вы можете просмотреть список позиций сайта ELEY, которые не подключены к системе мониторинга цен.</p>
        <?php
        if (isset($positions)) { ?>
            
        <p class="alert alert-warning">К системе мониторига не подключено позиций: <strong><?=count((array)$positions)?></strong>.</p>
        
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <th>Бренд</th>
                <th>Наименование</th>
                <th>Категория</th>
                <th>Код</th>
            </thead>
            <tbody>
            <?php
            foreach($positions as $code => $position_array) {
                echo "<tr>
                        <td>$position_array->brand</td>
                        <td>$position_array->name</td>
                        <td>$position_array->category</td>
                        <td>$code</td>
                      </tr>";
            }
            ?>
            </tbody>
        </table>
        
        <?php } else { ?>
            <p><a href="<?=Url::to(['monitor/eley-shop', 'get_positions' => true]) ?>" class="btn btn-sm btn-primary left-crop"><i class="fa fa-globe"></i> Показать позиции</a></p>
        <?php } ?>
    </div>
</div>

views/monitor/error-log.php
<?php

use yii\helpers\Url;
use \app\models\Price;


/* @var $this yii\web\View */

$this->title = 'Система мониторинга и корректировки цен';
?>

<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Журнал ошибок</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <table class="table table-bordered table-hover brands-list">
            <tbody>
                <tr>
                    <th>Описание ошибки</th>
                    <th>Время</th>                    
                </tr>
<?php
if (count($logs)) foreach($logs as $log) {
    echo "<tr>
            <td>$log->message</td>
            <td>".date("d.m.Y (H:i)", $log->date_time)."</td>
          </tr>";
} else echo "<tr><td colspan='2' class='text-center'>Ошибок не зафиксировано.</td></tr>";
?>
            </tbody>
        </table>
    </div><!-- /.box-body -->
    <div class="box-footer">
        <div class="row">
            <div class="col-xs-6"></div>
            <div class="col-xs-6 text-right">
                <p><a href="<?php echo Url::to(['monitor/error-log', 'clear' => true]); ?>" class="btn btn-sm btn-success left-crop"><i class="fa fa-trash"></i> Очистить журнал</a></p>
            </div>
        </div>
    </div><!-- box-footer -->
</div><!-- /.box -->

views/monitor/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/monitor/index.php
<?php

use yii\helpers\Url;
use \app\models\Price;

/* @var $this yii\web\View */

$this->title = 'Система мониторинга и корректировки цен';
?>

<div class="row">
    <div class="col-lg-3 col-xs-6">
      <!-- small box -->
      <div class="small-box bg-aqua-gradient">
        <div class="inner">
            <h3><?=$all_positions_count?></h3>

          <p>Позиций в системе</p>
        </div>
        <div class="icon">
          <i class="ion ion-bag"></i>
        </div>
        <a href="<?=Url::to(['monitor/catalogue']); ?>" class="small-box-footer">Перейти в каталог <i class="fa fa-arrow-circle-right"></i></a>
      </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <p>
          <strong>Отслеживаемые позиции:</strong>
        </p>

        <div class="progress-group">
          <span class="progress-text">MakeUp</span>
          <span class="progress-number"><b><?=$makeup_positions_count?></b>/<?=$all_positions_count?></span>

          <div class="progress sm">
            <div class="progress-bar progress-bar-aqua" style="width: <?=round($makeup_positions_count*100/$all_positions_count); ?>%"></div>
          </div>
        </div>
        <!-- /.progress-group -->
        <div class="progress-group">
          <span class="progress-text">Parfums</span>
          <span class="progress-number"><b><?=$parfums_positions_count?></b>/<?=$all_positions_count?></span>

          <div class="progress sm">
            <div class="progress-bar progress-bar-red" style="width: <?=round($parfums_positions_count*100/$all_positions_count); ?>%"></div>
          </div>
        </div>
        <!-- /.progress-group -->
        <div class="progress-group">
          <span class="progress-text">Lagrande</span>
          <span class="progress-number"><b><?=$lagrande_positions_count?></b>/<?=$all_positions_count?></span>

          <div class="progress sm">
            <div class="progress-bar progress-bar-green" style="width: <?=round($lagrande_positions_count*100/$all_positions_count); ?>%"></div>
          </div>
        </div>
        <!-- /.progress-group -->
        <div class="progress-group">
          <span class="progress-text">Parfumeria</span>
          <span class="progress-number"><b><?=$parfumeria_positions_count?></b>/<?=$all_positions_count?></span>

          <div class="progress sm">
            <div class="progress-bar progress-bar-yellow" style="width: <?=round($parfumeria_positions_count*100/$all_positions_count); ?>%"></div>
          </div>
        </div>
        <!-- /.progress-group -->
      </div>
</div>

views/monitor/login.php
<?php
use app\assets\AppAsset;

AppAsset::register($this);


/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;

$this->title = 'Вход в систему мониторинга';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="hold-transition lockscreen">
<?php $this->beginBody() ?>
<!-- Automatic element centering -->
<div class="lockscreen-wrapper">
  <div class="lockscreen-logo">
    <a href="/"><b>Мониторинг</b>Цен</a>
  </div>
  <!-- User name -->
  <div class="lockscreen-name">Eley.com.ua</div>

  <!-- START LOCK SCREEN ITEM -->
  <div class="lockscreen-item">
    <!-- lockscreen image -->
    <div class="lockscreen-image">
      <img src="/img/bazilik.png" alt="User Image">
    </div>
    <!-- /.lockscreen-image -->

    <!-- lockscreen credentials (contains the form) -->
    <form class="lockscreen-credentials" action='/index.php?r=monitor/login' method="post">
      <div class="input-group">
        <input type="hidden" name="username" value="eley" />
        <input name='password' type="password" class="form-control" placeholder="пароль">
        <input type="hidden" name="_csrf" value="<?=Yii::$app->request->getCsrfToken()?>" />
        <div class="input-group-btn">
          <button type="submit" class="btn"><i class="fa fa-arrow-right text-muted"></i></button>
        </div>
      </div>
    </form>
    <!-- /.lockscreen credentials -->

  </div>
  <!-- /.lockscreen-item -->
  <div class="help-block text-center">
    Введите пароль, чтобы авторизироваться
  </div>
  <div class="lockscreen-footer text-center">
    Copyright &copy; 2016 <b><a href="http://monitor.eley.com.ua" class="text-black">monitor.eley.com.ua</a></b><br>
    Все права защищены
  </div>
</div>
<!-- /.center -->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>